### ISSUE TITLE
Everyone who join the training please make a PR and add your name

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/LearningGitHub#51]
We did not manage to add all names to the document so please go ahead and make a PR as shown during the workshop!

**Comment by soerenthomsen** [comment]
@jkarstensen do you want to add your name also via a PR?

**Comment by soerenthomsen** [comment]
Who else did we miss?

**Comment by jkarstensen** [comment]
> 

no idea

**Comment by soerenthomsen** [comment]
@hassanimaryam would you like to make an own PR and add your name and GitHub page?

**Comment by hassanimaryam** [comment]
> Sorry to hear that you had issues with your connection during our GitHub training session @hassanimaryam
> 
> Are you able to make a Pull-Request and add your 

> Sorry to hear that you had issues with your connection during our GitHub training session @hassanimaryam
> 
> Are you able to make a Pull-Request and add your name?

Unfortunately I can't

**Comment by soerenthomsen** [comment]
Ok so let's organise another shorter session maybe today just after the T&S workshop? Will you be available?

**Comment by hassanimaryam** [comment]
> Ok so let's organise another shorter session maybe today just after the T&S workshop? Will you be available?
Tnank you Soeren

**Comment by soerenthomsen** [comment]
Sure! I made a new issue here: #54  Please indicate your interest there
